language:
    python
python:
    - 2.6
env:
    - KAFKA_VERSION=0.8.1
    - KAFKA_VERSION=0.8.1.1
before_install:
    - curl https://archive.apache.org/dist/kafka/${KAFKA_VERSION}/kafka_2.8.0-${KAFKA_VERSION}.tgz | tar xvz
    - cd kafka_2.8.0-{KAFKA_VERSION}
    - ./sbt update
    - ./sbt package
    - ./sbt assembly-package-dependency
    - bin/zookeeper-server-start.sh config/zookeeper.properties
    - bin/kafka-server-start.sh config/server.properties
script:
    - echo "success"
